import React from "react";
import { motion } from "framer-motion";
import {
  Brain,
  Sparkles,
  TrendingUp,
  ArrowRight,
} from "lucide-react";

import Card from "../../../ui/card/Card";
import { theme } from "../../../../design-system";

interface Recommendation {
  id: number;
  title: string;
  confidence: number;
  priority: "Critical" | "High" | "Medium";
}

const recommendations: Recommendation[] = [
  {
    id: 1,
    title: "Review delayed infrastructure projects",
    confidence: 98,
    priority: "Critical",
  },
  {
    id: 2,
    title: "Approve pending land acquisition files",
    confidence: 94,
    priority: "High",
  },
  {
    id: 3,
    title: "Review today's revenue opportunity report",
    confidence: 91,
    priority: "Medium",
  },
];

const priorityColor = (priority: Recommendation["priority"]) => {
  switch (priority) {
    case "Critical":
      return theme.colors.status.danger;

    case "High":
      return theme.colors.status.warning;

    default:
      return theme.colors.status.info;
  }
};

const AIExecutiveAdvisor: React.FC = () => {
  return (
    <Card
      variant="glass"
      size="lg"
    >
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          gap: theme.spacing.lg,
        }}
      >
        {/* Header */}

        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
          }}
        >
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: theme.spacing.md,
            }}
          >
            <Brain
              size={24}
              color={theme.colors.brand.primary}
            />

            <div>
              <div
                style={{
                  color: theme.colors.text.primary,
                  fontWeight: 600,
                  fontSize: 18,
                }}
              >
                AI Executive Advisor
              </div>

              <div
                style={{
                  color: theme.colors.text.secondary,
                  fontSize: 13,
                }}
              >
                Strategic recommendations generated by AI
              </div>
            </div>
          </div>

          <Sparkles
            size={20}
            color={theme.colors.brand.secondary}
          />
        </div>

        {/* Recommendations */}

        <div
          style={{
            display: "flex",
            flexDirection: "column",
            gap: theme.spacing.md,
          }}
        >
          {recommendations.map((item) => (
            <motion.div
              key={item.id}
              whileHover={{
                x: 4,
              }}
            >
              <div
                style={{
                  padding: theme.spacing.md,
                  borderRadius: theme.radius.md,
                  border: `1px solid ${theme.colors.border.primary}`,
                  background: "rgba(255,255,255,.04)",
                }}
              >
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                  }}
                >
                  <div
                    style={{
                      flex: 1,
                    }}
                  >
                    <div
                      style={{
                        color: theme.colors.text.primary,
                        fontWeight: 600,
                      }}
                    >
                      {item.title}
                    </div>

                    <div
                      style={{
                        marginTop: theme.spacing.sm,
                        display: "flex",
                        gap: theme.spacing.md,
                        color: theme.colors.text.secondary,
                        fontSize: 13,
                      }}
                    >
                      <span>
                        Confidence {item.confidence}%
                      </span>

                      <span
                        style={{
                          color: priorityColor(item.priority),
                          fontWeight: 600,
                        }}
                      >
                        {item.priority}
                      </span>
                    </div>
                  </div>

                  <ArrowRight
                    size={18}
                    color={theme.colors.text.secondary}
                  />
                </div>
              </div>
            </motion.div>
          ))}
        </div>

        {/* Footer */}

        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: theme.spacing.sm,
            color: theme.colors.brand.secondary,
            fontWeight: 600,
            fontSize: 13,
          }}
        >
          <TrendingUp size={16} />

          AI confidence improving continuously
        </div>
      </div>
    </Card>
  );
};

export default AIExecutiveAdvisor;