import { motion } from "framer-motion";
import {
  ArrowRight,
  BrainCircuit,
  CheckCircle2,
  Sparkles,
  Target,
} from "lucide-react";

import { recommendations } from "../data";

const getPriorityStyle = (priority: string) => {
  switch (priority) {
    case "Critical":
      return {
        badge: "bg-red-500/10 border-red-500/20 text-red-400",
      };

    case "High":
      return {
        badge: "bg-orange-500/10 border-orange-500/20 text-orange-400",
      };

    default:
      return {
        badge: "bg-emerald-500/10 border-emerald-500/20 text-emerald-400",
      };
  }
};

const getImpactStyle = (impact: string) => {
  switch (impact) {
    case "High":
      return "text-emerald-400";

    case "Medium":
      return "text-amber-400";

    default:
      return "text-slate-400";
  }
};

export default function AIRecommendations() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.45 }}
      className="rounded-2xl border border-slate-800 bg-slate-900/60 backdrop-blur-sm"
    >
      {/* Header */}

      <div className="flex items-center justify-between border-b border-slate-800 px-6 py-5">
        <div>
          <h3 className="text-lg font-semibold text-white">
            AI Recommendations
          </h3>

          <p className="mt-1 text-sm text-slate-400">
            Executive recommendations generated by the DAIP Intelligence Engine.
          </p>
        </div>

        <div className="rounded-full bg-cyan-500/10 p-3">
          <BrainCircuit className="h-5 w-5 text-cyan-400" />
        </div>
      </div>

      {/* Recommendations */}

      <div className="space-y-5 p-6">
        {recommendations.map((item, index) => {
          const priority = getPriorityStyle(item.priority);

          return (
            <motion.div
              key={item.id}
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{
                duration: 0.35,
                delay: index * 0.08,
              }}
              whileHover={{
                y: -3,
              }}
              className="rounded-xl border border-slate-800 bg-slate-950/40 p-5 transition-all duration-300 hover:border-cyan-500/30"
            >
              <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
                {/* Left */}

                <div className="flex-1">
                  <div className="flex flex-wrap items-center gap-3">
                    <Sparkles className="h-5 w-5 text-cyan-400" />

                    <h4 className="text-base font-semibold text-white">
                      {item.title}
                    </h4>

                    <span
                      className={`rounded-full border px-3 py-1 text-xs font-semibold ${priority.badge}`}
                    >
                      {item.priority}
                    </span>
                  </div>

                  <p className="mt-4 leading-7 text-slate-400">
                    {item.description}
                  </p>

                  <div className="mt-5 flex items-center gap-3">
                    <Target className="h-4 w-4 text-cyan-400" />

                    <span className="text-sm text-slate-400">
                      Expected Impact:
                    </span>

                    <span
                      className={`font-semibold ${getImpactStyle(item.impact)}`}
                    >
                      {item.impact}
                    </span>
                  </div>
                </div>

                {/* Action */}

                <div className="flex flex-col items-end gap-3">
                  <button className="inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-4 py-2 text-sm font-semibold text-slate-950 transition hover:bg-cyan-400">
                    Review
                    <ArrowRight className="h-4 w-4" />
                  </button>

                  <button className="inline-flex items-center gap-2 rounded-xl border border-slate-700 px-4 py-2 text-sm text-slate-300 transition hover:border-emerald-500 hover:text-white">
                    <CheckCircle2 className="h-4 w-4" />
                    Accept
                  </button>
                </div>
              </div>
            </motion.div>
          );
        })}
      </div>

      {/* Footer */}

      <div className="flex items-center justify-between border-t border-slate-800 px-6 py-4">
        <span className="text-sm text-slate-500">
          Recommendations refresh after every AI analysis cycle.
        </span>

        <span className="text-sm font-medium text-cyan-400">
          Powered by DAIP Intelligence Engine
        </span>
      </div>
    </motion.div>
  );
}