import { motion } from "framer-motion";
import {
  BrainCircuit,
  CheckCircle2,
  ShieldCheck,
  Target,
} from "lucide-react";

import { engineHealth } from "../data";

const confidenceItems = [
  {
    title: "Prediction Accuracy",
    value: `${engineHealth.accuracy}%`,
    description: "Average accuracy across AI models",
    icon: Target,
    color: "text-cyan-400",
    progress: engineHealth.accuracy,
  },
  {
    title: "Model Reliability",
    value: "99.2%",
    description: "Stable model execution rate",
    icon: ShieldCheck,
    color: "text-emerald-400",
    progress: 99.2,
  },
  {
    title: "Decision Confidence",
    value: "97.8%",
    description: "Average confidence of recommendations",
    icon: BrainCircuit,
    color: "text-violet-400",
    progress: 97.8,
  },
];

export default function DecisionConfidence() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.45 }}
      className="rounded-2xl border border-slate-800 bg-slate-900/60 backdrop-blur-sm"
    >
      {/* Header */}

      <div className="flex items-center justify-between border-b border-slate-800 px-6 py-5">
        <div>
          <h3 className="text-lg font-semibold text-white">
            Decision Confidence
          </h3>

          <p className="mt-1 text-sm text-slate-400">
            Reliability metrics generated by the DAIP AI Engine.
          </p>
        </div>

        <div className="rounded-full bg-cyan-500/10 p-3">
          <BrainCircuit className="h-5 w-5 text-cyan-400" />
        </div>
      </div>

      {/* Body */}

      <div className="space-y-6 p-6">
        {confidenceItems.map((item, index) => {
          const Icon = item.icon;

          return (
            <motion.div
              key={item.title}
              initial={{ opacity: 0, x: -15 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{
                duration: 0.35,
                delay: index * 0.08,
              }}
              className="rounded-xl border border-slate-800 bg-slate-950/40 p-5"
            >
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                  <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-slate-800">
                    <Icon className={`h-6 w-6 ${item.color}`} />
                  </div>

                  <div>
                    <h4 className="font-semibold text-white">
                      {item.title}
                    </h4>

                    <p className="mt-1 text-sm text-slate-500">
                      {item.description}
                    </p>
                  </div>
                </div>

                <div className="text-right">
                  <div className={`text-2xl font-bold ${item.color}`}>
                    {item.value}
                  </div>

                  <div className="text-xs text-slate-500">
                    Confidence Score
                  </div>
                </div>
              </div>

              <div className="mt-5">
                <div className="mb-2 flex justify-between text-xs text-slate-500">
                  <span>Confidence Level</span>
                  <span>{item.progress}%</span>
                </div>

                <div className="h-2 overflow-hidden rounded-full bg-slate-800">
                  <motion.div
                    initial={{ width: 0 }}
                    animate={{
                      width: `${item.progress}%`,
                    }}
                    transition={{
                      duration: 1,
                      delay: 0.2 + index * 0.1,
                    }}
                    className="h-full rounded-full bg-gradient-to-r from-cyan-500 via-sky-400 to-emerald-400"
                  />
                </div>
              </div>
            </motion.div>
          );
        })}
      </div>

      {/* Footer */}

      <div className="flex items-center justify-between border-t border-slate-800 px-6 py-4">
        <div className="flex items-center gap-2 text-sm text-emerald-400">
          <CheckCircle2 className="h-4 w-4" />
          All AI confidence metrics are within operational thresholds.
        </div>

        <span className="text-sm text-slate-500">
          Updated in real time
        </span>
      </div>
    </motion.div>
  );
}